spring:
  application:
    name: spring-security-jwt
server:
  port: 8080
  servlet:
    path: /
jwt:
  token:
    secret: secret
    expiration: 63500
manage:
  user:
    username: admin
    password: 123456
logging:
  level: debug
#调试springsecurity 最好开启，可以查看所有的处理流程，生产关闭
debug: true